spring.application.name=cachefy
server.port= 8088
spring.datasource.url=jdbc:postgresql://localhost:5432/cachefy
spring.datasource.username=psql
spring.datasource.password=psql123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379
